//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementSystem.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectManagementSystem.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入力データを登録できませんでした。.
        /// </summary>
        public static string E001 {
            get {
                return ResourceManager.GetString("E001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は必須項目です。.
        /// </summary>
        public static string E002 {
            get {
                return ResourceManager.GetString("E002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}の入力形式に誤りがあります。.
        /// </summary>
        public static string E003 {
            get {
                return ResourceManager.GetString("E003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}を選択してください。.
        /// </summary>
        public static string E004 {
            get {
                return ResourceManager.GetString("E004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to この内容で登録します。\nよろしいですか？.
        /// </summary>
        public static string E005 {
            get {
                return ResourceManager.GetString("E005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 既に選択されている{0}です。.
        /// </summary>
        public static string E006 {
            get {
                return ResourceManager.GetString("E006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}に誤りがあるか、登録されていない{1}です。.
        /// </summary>
        public static string E007 {
            get {
                return ResourceManager.GetString("E007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 既に使用されている{0}です。{1}は重複登録できません。.
        /// </summary>
        public static string E008 {
            get {
                return ResourceManager.GetString("E008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 既に使用されている{0}です。{1}は重複登録できません。.
        /// </summary>
        public static string E009 {
            get {
                return ResourceManager.GetString("E009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイル形式が不正です。使用できるファイル形式は{0}です。.
        /// </summary>
        public static string E010 {
            get {
                return ResourceManager.GetString("E010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルサイズが大きすぎます。{0}のファイルを選択してください。.
        /// </summary>
        public static string E011 {
            get {
                return ResourceManager.GetString("E011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メール送信に失敗しました。.
        /// </summary>
        public static string E012 {
            get {
                return ResourceManager.GetString("E012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入力回数上限を超えましたのでアカウントはロックされました。.
        /// </summary>
        public static string E013 {
            get {
                return ResourceManager.GetString("E013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to このアカウントはロックされています。システム管理者にお問い合わせください。.
        /// </summary>
        public static string E014 {
            get {
                return ResourceManager.GetString("E014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}の{1}に失敗しました。.
        /// </summary>
        public static string E015 {
            get {
                return ResourceManager.GetString("E015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 既に使用されている{0}です。別の{1}を入力してください。.
        /// </summary>
        public static string E016 {
            get {
                return ResourceManager.GetString("E016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}を選択してください。.
        /// </summary>
        public static string E017 {
            get {
                return ResourceManager.GetString("E017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}を{1}しました。.
        /// </summary>
        public static string E018 {
            get {
                return ResourceManager.GetString("E018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は{1}～{2}の範囲で入力してください。.
        /// </summary>
        public static string E019 {
            get {
                return ResourceManager.GetString("E019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は{1}文字以内で入力してください。.
        /// </summary>
        public static string E020 {
            get {
                return ResourceManager.GetString("E020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルサイズが大きすぎます。{0}のファイルを選択してください。.
        /// </summary>
        public static string E021 {
            get {
                return ResourceManager.GetString("E021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}と{1}が一致しません。.
        /// </summary>
        public static string E022 {
            get {
                return ResourceManager.GetString("E022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は6～32文字の範囲で入力してください。.
        /// </summary>
        public static string E023 {
            get {
                return ResourceManager.GetString("E023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 期間が変更されました。\nアサイン一覧、売上一覧、支払一覧の内容が 変更 されますがよろしいですか？.
        /// </summary>
        public static string E024 {
            get {
                return ResourceManager.GetString("E024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 消費税率を変更しますか？.
        /// </summary>
        public static string E025 {
            get {
                return ResourceManager.GetString("E025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は特別な記号と空白を含んではいけません。.
        /// </summary>
        public static string E026 {
            get {
                return ResourceManager.GetString("E026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 期間終了日は期間開始日より未来の日付を入力して下さい。.
        /// </summary>
        public static string E027 {
            get {
                return ResourceManager.GetString("E027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}の{1}に誤りがあります。.
        /// </summary>
        public static string E028 {
            get {
                return ResourceManager.GetString("E028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入力された内容に誤りがあるか、登録されていないアカウントです。.
        /// </summary>
        public static string E029 {
            get {
                return ResourceManager.GetString("E029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 期間は1年以内で設定してください。.
        /// </summary>
        public static string E030 {
            get {
                return ResourceManager.GetString("E030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 他のユーザーによって更新されたため登録に失敗しました。&lt;br /&gt;最新情報を取得しますか？.
        /// </summary>
        public static string E031 {
            get {
                return ResourceManager.GetString("E031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アサインされているプロジェクトが存在しません。.
        /// </summary>
        public static string E032 {
            get {
                return ResourceManager.GetString("E032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登録されている社員No.とCSVファイルの社員No.が一致しません。.
        /// </summary>
        public static string E033 {
            get {
                return ResourceManager.GetString("E033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSVの形式が不正です。.
        /// </summary>
        public static string E034 {
            get {
                return ResourceManager.GetString("E034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV取込処理に失敗しました。.
        /// </summary>
        public static string E035 {
            get {
                return ResourceManager.GetString("E035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}に値が設定されていません。.
        /// </summary>
        public static string E036 {
            get {
                return ResourceManager.GetString("E036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登録されている社員No.とCSVファイルの社員No.が一致しません。.
        /// </summary>
        public static string E037 {
            get {
                return ResourceManager.GetString("E037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}の形式が不正です。.
        /// </summary>
        public static string E038 {
            get {
                return ResourceManager.GetString("E038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は{1}より未来の時間を入力して下さい。.
        /// </summary>
        public static string E039 {
            get {
                return ResourceManager.GetString("E039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}のデータが重複しています。.
        /// </summary>
        public static string E040 {
            get {
                return ResourceManager.GetString("E040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 稼働実績の合計時間が設定上限を超えています。.
        /// </summary>
        public static string E041 {
            get {
                return ResourceManager.GetString("E041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSVファイルの形式に誤りがあります。.
        /// </summary>
        public static string E042 {
            get {
                return ResourceManager.GetString("E042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 変更された内容はありません。.
        /// </summary>
        public static string E043 {
            get {
                return ResourceManager.GetString("E043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 接続の有効時間が切れました。再度ログインしなおしてください。.
        /// </summary>
        public static string E044 {
            get {
                return ResourceManager.GetString("E044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}の登録に失敗しました。.
        /// </summary>
        public static string E045 {
            get {
                return ResourceManager.GetString("E045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイル形式に誤りがあります。.
        /// </summary>
        public static string E046 {
            get {
                return ResourceManager.GetString("E046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSVファイルの書式に誤りがあります。&lt;br&gt;CSVファイルの内容を確認してください。.
        /// </summary>
        public static string E047 {
            get {
                return ResourceManager.GetString("E047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入力したパスワードと確認パスワードが一致していません。.
        /// </summary>
        public static string E048 {
            get {
                return ResourceManager.GetString("E048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 稼動実績と勤務時間に差異があるため本登録できません。.
        /// </summary>
        public static string E049 {
            get {
                return ResourceManager.GetString("E049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSVデータの取り込みが完了しました。.
        /// </summary>
        public static string E050 {
            get {
                return ResourceManager.GetString("E050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新処理に失敗しました。.
        /// </summary>
        public static string E051 {
            get {
                return ResourceManager.GetString("E051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 複数のプロジェクトが選択されているため複写できません。.
        /// </summary>
        public static string E052 {
            get {
                return ResourceManager.GetString("E052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 変更前と同一のパスワードは設定できません。.
        /// </summary>
        public static string E053 {
            get {
                return ResourceManager.GetString("E053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添付ファイルの表示名を設定してください。.
        /// </summary>
        public static string E054 {
            get {
                return ResourceManager.GetString("E054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指定のファイルが見つかりません。システム管理者にお問い合わせください。.
        /// </summary>
        public static string E055 {
            get {
                return ResourceManager.GetString("E055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 掲載終了日は掲載開始日より未来の日付を入力して下さい。.
        /// </summary>
        public static string E056 {
            get {
                return ResourceManager.GetString("E056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入力されていないサブカテゴリがあります。.
        /// </summary>
        public static string E057 {
            get {
                return ResourceManager.GetString("E057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サブカテゴリが設定されていません。.
        /// </summary>
        public static string E058 {
            get {
                return ResourceManager.GetString("E058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 既に使用されているフェーズのため削除できません。.
        /// </summary>
        public static string E059 {
            get {
                return ResourceManager.GetString("E059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 既に使用されている適用開始日です。適用開始日は重複登録できません。.
        /// </summary>
        public static string E060 {
            get {
                return ResourceManager.GetString("E060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全ての曜日を規定休日に設定することはできません。.
        /// </summary>
        public static string E061 {
            get {
                return ResourceManager.GetString("E061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 営業日数が0になる月があります。休日設定を見直してください。.
        /// </summary>
        public static string E062 {
            get {
                return ResourceManager.GetString("E062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 既に使用されているサブカテゴリのため削除できません。.
        /// </summary>
        public static string E063 {
            get {
                return ResourceManager.GetString("E063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログアウトします。\nよろしいですか？.
        /// </summary>
        public static string E064 {
            get {
                return ResourceManager.GetString("E064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 理由を備考欄に入力してください。  .
        /// </summary>
        public static string E065 {
            get {
                return ResourceManager.GetString("E065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 契約プランの期限が切れているか無効になっています。.
        /// </summary>
        public static string E066 {
            get {
                return ResourceManager.GetString("E066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}登録数の上限を超えたため登録できません。.
        /// </summary>
        public static string E067 {
            get {
                return ResourceManager.GetString("E067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 対象の諸経費種別は現在使用されているため削除できません。.
        /// </summary>
        public static string E068 {
            get {
                return ResourceManager.GetString("E068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取引先CSVが不正です。.
        /// </summary>
        public static string E0681 {
            get {
                return ResourceManager.GetString("E0681", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 対象のプロジェクトは稼働実績が入力されているため変更できません。.
        /// </summary>
        public static string E069 {
            get {
                return ResourceManager.GetString("E069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSVファイルの読み込みに失敗しました。.
        /// </summary>
        public static string E070 {
            get {
                return ResourceManager.GetString("E070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to チェック起点曜日が設定されていません。.
        /// </summary>
        public static string E071 {
            get {
                return ResourceManager.GetString("E071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 処理中にシステムエラーが発生しました。.
        /// </summary>
        public static string E999 {
            get {
                return ResourceManager.GetString("E999", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入力したメールアドレスに新しいパスワードを送信しました。.
        /// </summary>
        public static string I001 {
            get {
                return ResourceManager.GetString("I001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワード再発行.
        /// </summary>
        public static string I002 {
            get {
                return ResourceManager.GetString("I002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;パスワードを変更するには、以下のリンクをクリックしてください:&lt;/p&gt;
        ///&lt;p&gt;{0}&lt;/p&gt;
        ///&lt;p&gt;ログイン:&lt;span style=&quot;font-weight: bold;&quot;&gt; {1}&lt;/span&gt;&lt;/p&gt;
        ///&lt;hr style=&quot;width: 43%;margin-left: 0px;&quot;&gt;
        ///お問い合わせはこちら
        ///&lt;br&gt;
        ///{2}.
        /// </summary>
        public static string I003 {
            get {
                return ResourceManager.GetString("I003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}を{1}しました。.
        /// </summary>
        public static string I004 {
            get {
                return ResourceManager.GetString("I004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワードが{0}ヶ月以上変更されていません。\nパスワードを変更してください。.
        /// </summary>
        public static string I005 {
            get {
                return ResourceManager.GetString("I005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to この内容で登録します。\nよろしいですか？.
        /// </summary>
        public static string I006 {
            get {
                return ResourceManager.GetString("I006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}を{1}しました。.
        /// </summary>
        public static string I007 {
            get {
                return ResourceManager.GetString("I007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV取込処理を行うと勤務開始時間、勤務終了時間は上書きされますがよろしいですか？.
        /// </summary>
        public static string I008 {
            get {
                return ResourceManager.GetString("I008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV取込処理が完了しました。.
        /// </summary>
        public static string I009 {
            get {
                return ResourceManager.GetString("I009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 変更内容が保存されていませんがよろしいですか？.
        /// </summary>
        public static string I010 {
            get {
                return ResourceManager.GetString("I010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 住所情報が上書きされますがよろしいですか？.
        /// </summary>
        public static string I011 {
            get {
                return ResourceManager.GetString("I011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 郵便番号に該当する住所情報が見つかりません。.
        /// </summary>
        public static string I012 {
            get {
                return ResourceManager.GetString("I012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワードを変更してください。.
        /// </summary>
        public static string I013 {
            get {
                return ResourceManager.GetString("I013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 既に使用されているタグのため変更できません。.
        /// </summary>
        public static string I014 {
            get {
                return ResourceManager.GetString("I014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 郵便番号を入力して下さい。.
        /// </summary>
        public static string I015 {
            get {
                return ResourceManager.GetString("I015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 郵便番号に誤りがあります。.
        /// </summary>
        public static string I016 {
            get {
                return ResourceManager.GetString("I016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワードの再設定が完了しました。\nログイン画面に遷移します。.
        /// </summary>
        public static string I017 {
            get {
                return ResourceManager.GetString("I017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URLが不正です。
        ///再度Eメールを確認してください。.
        /// </summary>
        public static string I018 {
            get {
                return ResourceManager.GetString("I018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 稼働実績が未登録の日付に対して取込処理を行います。\nよろしいですか？.
        /// </summary>
        public static string I019 {
            get {
                return ResourceManager.GetString("I019", resourceCulture);
            }
        }
    }
}
